#
#	Makefile for XLR parser.
#

# CFLAGS = -DDEBUG
# CFLAGS = -O
CC	   = g++
CFLAGS = -g -static

# SOURCES = xlr.y

all  :	main main.o

# x2lib :	x2lib.o xlr.o 
# 	gcc $(CFLAGS) x2lib.o xlr.o -o x2lib -lm

# xlr :	xlr.o 
# 	gcc $(CFLAGS) -c xlr.c

# xlr.o : xlr.c

# xlr.c : xlr.y
# 	bison -t -v -d xlr.y 
# 	cp xlr.tab.c xlr.c

# dist:
# 	shar xlr.y xlr.h  XLR_Format.txt makefile x2lib.c > xlr.sh
# clean :
# 	rm *.o xlr.c xlr.output xlr.tab.c xlr.tab.h x2lib
